### ISSUE TITLE
This dependency was not found:  * firebase in ./src/plugins/firebase.js  To install it, you can run: npm install --save firebase

### ISSUE THREAD

**Issue by resourceldg** [CristalT/quasar-app-firebase-auth#2]
im using quasar cli 15.10 on ubuntu 18

first im creating my project with quasar init myproj
then copy and **reemplace** your files and direcories (src,etc etc...)
and run npm install in myproj
and then execute quasar dev 
but is not working

output:
This dependency was not found:

* firebase in ./src/plugins/firebase.js

To install it, you can run: npm install --save firebase

Thanks

**Comment by CristalT** [comment]
Check if the firebase plugin is setted in quasar.conf.js file at the plugins array:
`
...
plugins: ['firebase']
...
`
